### PR TITLE
Convert ES6 features to ES5 code so that uglify will not choke

### LINKED ISSUE #27: Uglify fails to minify
Right now in the [Bitcentive](https://github.com/donejs/bitcentive) app can't build because uglify chokes on ES6 features used in can-connect-feathers.

I see 2 possible solutions:

1. don't use ES6 features in can-connect-feathers src
2. transpile the source code to ES5 when publishing

### PR DESCRIPTION
**Pull request by BigAB**
Fixes #27 

This PR leaves a bad taste in my mouth, but it is the easiest way to move forward until we can implement a better solution.

This just converts ES6 features to ES5, but we should really consider a build step to do this for us so we can continue to use ES6 in the source code.

### CODE REVIEW

File: feathers/feathers.js [hunk 1]
```diff
@@ -9,17 +9,18 @@ module.exports = connect.behavior('data/feathers', function () {
   var service = this.feathersService;
 
   // Connect to realtime events.
-  service.on('created', message => this.createInstance(message));
-  service.on('updated', message => this.updateInstance(message));
-  service.on('patched', message => this.updateInstance(message));
-  service.on('removed', message => this.destroyInstance(message));
+	var self = this;
```
Comment (BigAB) [inline feathers/feathers.js]: Fixed and force-pushed

**Comment by marshallswain** [comment]
published as `can-connect-feathers@2.0.0-beta.5`
